# Generated by Django 3.2.7 on 2021-09-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
