# Generated by Django 3.2.7 on 2021-09-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
