# Generated by Django 3.2.7 on 2021-10-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20211003_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state_index',
            field=models.IntegerField(default=0),
        ),
    ]
