# Generated by Django 3.2.7 on 2021-10-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_alter_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='state_index',
        ),
        migrations.AddField(
            model_name='task',
            name='state_text',
            field=models.CharField(default='', max_length=20),
        ),
    ]
