# Generated by Django 3.2.7 on 2021-10-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_auto_20211010_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
