# Generated by Django 3.2.7 on 2021-10-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_alter_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='name',
        ),
    ]
